---
# Source: generic-app/templates/namespace.yaml
apiVersion: v1
kind: Namespace
metadata:
  name:
---
# Source: generic-app/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: myapp-config
  namespace: 
  labels:
    app: myapp
data:
  MONGO_URI: "mongodb://localhost:27017"
---
# Source: generic-app/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: myapp
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: myapp
---
# Source: generic-app/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: myapp
  labels:
    app: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: "nginx:latest"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: NODE_ENV
              value: "uat"
            - name: MONGO_URI
              # Todo fix the hardcoded indentation 16
              valueFrom:
                secretKeyRef:
                  key: CONNECTION_STRING
                  name: db-connection
            # ConfigMap
            - name: MONGO_URI
              valueFrom:
                configMapKeyRef:
                  name: myapp-config
                  key: MONGO_URI

          # Mount ExternalSecret as a file

      # Volumes for ExternalSecret
