{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.externalSecrets.secretName }}
  namespace: {{ .Values.appName }}
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: {{ .Values.externalSecrets.secretStore.name }}
    kind: {{ .Values.externalSecrets.secretStore.kind }}
  target:
    name: {{ .Values.externalSecrets.secretName }}
  data:
    - secretKey: app-config
      remoteRef:
        key: {{ .Values.externalSecrets.remoteKey }}
{{- end }}
